# Generated by Django 3.0.6 on 2020-05-09 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import partial_state.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.IntegerField()),
                ('column2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestAPartialState',
            fields=[
                ('column1', models.IntegerField(null=True)),
                ('column2', models.CharField(max_length=10, null=True)),
                ('partial_state_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tests_testa_partialstate',
                'ordering': ('-partial_state_id',),
                'get_latest_by': 'partial_state_id',
            },
            bases=(models.Model, partial_state.models.PartialStateMixin),
        ),
        migrations.CreateModel(
            name='TestB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.IntegerField()),
                ('column2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestBPartialState',
            fields=[
                ('column1', models.IntegerField(null=True)),
                ('column2', models.CharField(max_length=10, null=True)),
                ('partial_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('partial_state_expiry', models.DateTimeField(default=partial_state.models.ExpiryDefault(datetime.timedelta(days=3)))),
            ],
            options={
                'db_table': 'tests_testb_partialstate',
                'ordering': ('-partial_state_id',),
                'get_latest_by': 'partial_state_id',
            },
            bases=(models.Model, partial_state.models.PartialStateMixin),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('somenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.User')),
                ('username', models.CharField(max_length=50)),
                ('street_address', models.CharField(default=None, max_length=250)),
                ('postal_code', models.IntegerField()),
            ],
            bases=('tests.user',),
        ),
        migrations.CreateModel(
            name='ProfilePartialState',
            fields=[
                ('username', models.CharField(max_length=50, null=True)),
                ('street_address', models.CharField(default=None, max_length=250, null=True)),
                ('postal_code', models.IntegerField(null=True)),
                ('partial_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tests.User')),
            ],
            options={
                'db_table': 'tests_profile_partialstate',
                'ordering': ('-partial_state_id',),
                'get_latest_by': 'partial_state_id',
            },
            bases=(models.Model, partial_state.models.PartialStateMixin),
        ),
    ]
